server {
    listen 80;
    server_name vibeer.com www.vibeer.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name vibeer.com www.vibeer.com;

    ssl_certificate /certs/real/fullchain.pem;
    ssl_certificate_key /certs/real/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;
    client_max_body_size 100M;

    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy no-referrer always;

    location /assets/ {
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        add_header Cache-Control "no-store";
        try_files $uri $uri/ /index.html;
    }
}